Added named export `proj4` support to index.js
proj4js/proj4js pull request #477
Opened 2024-09-15 19:22 UTC by Beilinson

Fixes #476 

I hope this can be merged soon, as this issue is actively breaking unit tests in our GIS projects, and additionally is good practice to not have only default exports

2024-09-16 10:34 UTC, ahocevar requested changes

2024-09-16 10:34 UTC, ahocevar commented on package.json
> +  "version": "2.12.3-alpha",
Please remove this change - that will be done as part of release management.

2024-09-17 09:50 UTC, ahocevar approved these changes

2024-09-17 09:51 UTC, ahocevar requested changes
As you can see, this breaks the build.

2024-09-17 09:55 UTC, Beilinson commented
Yep, looking into it locally

2024-09-19 17:47 UTC, Beilinson commented
From my local tests this works, and also manages to fix the problem with jest in a different way, by exposing shimming the .default property that some parsers use when transforming ESM code to CJS.

I noticed that this is the same change as from #263 which is 7 years old, any reason that wasn't ever merged?

2024-09-19 19:45 UTC, ahocevar commented
It's really about time to update the build system - along the lines of #462, but getting rid of grunt entirely.

In the meantime, I think a safer change would be to create a separate entry point file for rollup (e.g. `./rollup/index.js`), which imports `proj4` from `../lib/index.js` and applies the hack you're proposing. Then you could point rollup to `rollup/index.js` instead of `lib/index.js` in the `Gruntfile`.

Then when updating the build system, we just get rid of `rollup/index.js`, and everything should work without this hack.

2024-09-24 19:33 UTC, Beilinson commented
having done some more tests, I realized that what this PR achieves can also be done by enabling [esModuleInterop](https://www.typescriptlang.org/tsconfig/esModuleInterop.html) which does exactly what this fixes ascribes. Closing this, if you would like any help with continuing #462 (for example, upgrading to jest as well, which supercedes mocha) I would be glad to help

2024-09-24 19:33 UTC, closed without merging

2024-09-24 19:46 UTC, ahocevar commented
@Beilinson I'd prefer vitest over jest, but help is always appreciated. Thanks!